export const SET_USER_REGISTER_BEGIN = 'SET_USER_REGISTER_BEGIN';
export const SET_USER_REGISTER_SUCCESS = 'SET_USER_REGISTER_SUCCESS';
export const SET_USER_REGISTER_ERROR = 'SET_USER_REGISTER_ERROR' 